services:
    postgres:
        image: postgres:latest
        env_file:
            - env/postgres.env
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql
            - ./postgres/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql

    rest-api:
        depends_on:
            - postgres
        build:
            context: ../target/
            dockerfile: ../web-pos-docker/rest-api/Dockerfile
        env_file:
            - env/rest-api.env
            - env/postgres.env
        ports:
            - "8000:8000"
        volumes:
            -   ./volumes/rest-api-logs:/app/logs

volumes:
    postgres_data: